# -*- coding: utf-8 -*-
"""Game SUIT (Rock, Paper, Scissor, Lizard, Spock).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FaixNbUhdA9-gGDzvydWo-vqhd3lMI1
"""

print('''SELAMAT DATANG DI GAME SUIT
Pada Game Ini Terdapat 5 Pilihan Simbol
1. Batu
2. Gunting
3. Kertas
4. Kadal
5. Spock \n''')

print('''Aturan dalam game ini yaitu:
- Gunting memotong Kertas
- Kertas membungkus Batu
- Batu menghancurkan Kadal
- Kadal meracuni Spock
- Spock menghancurkan Gunting
- Gunting memenggal Kadal
- Kadal memakan kertas
- Kertas menangkal Spock
- Spock menguapkan Batu
- Batu menghancurkan Gunting
''')

import random

main = int(input("Mau suit berapa kali? \t"))
score_user = 0
score_computer = 0

while (main > 0 ):
  user = input("\nMasukkan pilihan (batu, gunting, kertas, spock, kadal):\t ")
  if(user != "batu" and user != "gunting" and  user != "kertas" and  user != "spock" and  user != "kadal"):
    print("Masukkan pilihan yang sesuai")
    continue
  pilihan = ["batu", "gunting", "kertas", "spock", "kadal" ]
  computer = random.choice(pilihan)
  print("Pilihan User:\t\t", user, "\nPilihan Komputer:\t", computer)

  if user == computer:
    print("DRAW")
    print("\nSKOR SEMENTARA")
    print("Skormu:\t\t", score_user)
    print("Skor Komputer:\t", score_computer)

  elif user=="batu":
    if computer=="gunting":
      print("Batu menghancurkan Gunting!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kertas":
      print("Kertas membungkus batu!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="spock":
      print("Spock menguapkan batu!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kadal":
      print("Batu menghancurkan kadal!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
  
  elif user=="gunting":
    if computer=="batu":
      print("Batu menghancurkan gunting!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kertas":
      print("Gunting memotong kertas!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="spock":
      print("Spock menghancurkan gunting!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kadal":
      print("Gunting memenggal kadal!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
  
  elif user=="kertas":
    if computer=="batu":
      print("Kertas membungkus batu!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="gunting":
      print("Gunting memotong kertas!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="spock":
      print("Kertas menangkal spock!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kadal":
      print("Kadal memakan kertas!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)

  elif user=="spock":
    if computer=="batu":
      print("Spock menguapkan batu!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="gunting":
      print("Spock menghancurkan gunting!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kertas":
      print("Kertas menangkal spock!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kadal":
      print("Kadal meracuni spock!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)

  elif user=="kadal":
    if computer=="batu":
      print("Batu menghancurkan kadal!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="gunting":
      print("Gunting memenggal kadal!, Kamu Kalah!")
      score_computer += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="kertas":
      print("Kadal memakan kertas!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
    elif computer=="spock":
      print("Kadal meracuni spock!, Kamu Menang!")
      score_user += 1
      print("\nSKOR SEMENTARA")
      print("Skormu:\t\t", score_user)
      print("Skor Komputer:\t", score_computer)
  main -= 1


if score_user == score_computer:
  print("\nKALIAN SERI")
elif score_user > score_computer:
  print("\nKAMU MENANG")
else:
  print("\nKAMU KALAH")

