# -*- coding: utf-8 -*-
"""Game Tebak Angka

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXjig-2UXdH1KaQDS3yC1QrtL3rhXL6Y
"""

import random

angka = random.randint(1,10)
chance = 5
i = 0

print("SELAMAT DATANG DI GAME TEBAK ANGKA")
print('''Cara Bermain
- Inputkan angka tebakan anda
- Anda memiliki 5 kesempatan
- Jika kesempatan habis maka Anda kalah \n\n''')

while(chance > 0):
    tebakan = int(input("Masukkan angka tebakan Anda: "))   
    i += 1
    if (tebakan > angka ):
        print("Tebakan Terlalu Besar")
    elif (tebakan < angka):
        print("Tebakan Terlalu Kecil")
    elif (tebakan == angka):
        print("Anda Berhasil Menebak")
        break
    chance -= 1
    print("Sisa: ", chance, "Kesempatan \n")

    if(chance == 0):
        print("ANDA KALAH")

print("Anda melakukan", i, "kali tebakan")

